"""图标文件名索引（从 Gitee mytv-android/myTVlogo 实测快照，2026-09-22）。

============================================================
【FROZEN 2026-09-23】本文件即日起冻结，不再扩充、不再修改。
  冻结时的条目数：789
  冻结时的 sha256：
    791abc0a2d79fa09cfbaf83d357c9e511af44458b3feeb59558b6d0d382b2180
  守卫断言位置：test_probe_v4.py R21 章节
    - 断言条目数 == 789
    - 断言 sha256 == 上述值
  两条断言同时存在，防止"意外维护"（少加一条、改个名字、重跑快照）
  无声地改变匹配行为。

【为什么冻结，而不是继续扩库】
  R21 起台标主线改为**直采上游 channelIcon**（实测覆盖 201/305 = 65.9%），
  本文件降级为**兜底通道**（R20 实测在真实频道名上命中 23.6%）。
  - 上游字段权威、实时、随源站变更自动跟随 —— 且**零维护**。
  - 扩库是人力活，且永远滞后于源站变更；扩来的命中率不如直采。
  所以：新增台标需求一律走上游 channelIcon，**不接受本文件的索引补丁**。
  保留本文件仅因为：已建成资产白用，直采为空时拉一把不亏。

【兜底链路维持 R20.1 三层降级不变】
  1. 模块导入 try/except（文件缺失 → _FallbackLogoIndex）
  2. 调用点保护（get_logo_url 内 try）
  3. build_m3u 循环体保护
  R21 新增第四层：resolve_logo 内对兜底通道再包 try。
  原则不变 —— **图标可以全丢，m3u 必须完整产出来。**
============================================================

【这是什么】
  789 条 `归一化键 -> 库中真实文件名` 的映射。它是 `gx_epg_fetch.get_logo_url()`
  的**匹配字典**，让图标匹配**完全离线**：不调 Gitee API、不发任何网络请求。

【为什么不运行时拉目录】
  1. 这是封版项目，云端是无人值守定时任务。引入一个"每次跑都要访问 Gitee
     API"的依赖，等于给自己的发布链路插了一根会断的网线 —— Gitee 限流/改版
     那天，图标全丢还是小事，**整个 export-backup 失败**才是大事。
  2. 图标只是播放器的装饰，**丢了不影响播放**。用固定的快照换取
     100% 可预测的行为，是正确取舍。
  3. 离线可测：单测直接注入这份索引，零网络。

【怎么更新这份快照】
  库里新增频道图标后（比如想加"广西卫视"），两种做法：
    a) 只改 `_EXTRA`（下面），加一行 `"guangxi": "广西卫视"` —— 最省事，推荐。
    b) 重新抓快照覆盖 `_INDEX`：
       curl -sL "https://gitee.com/api/v5/repos/mytv-android/myTVlogo/contents/img?per_page=1000"
       （然后跑一遍归一化脚本，见 tools/README 的说明）

【归一化规则】
  键 = 原名转小写 → 只保留 [a-z0-9中文+] → 其余（空格/-/_/./括号）全删。
  这样 `CCTV-1` / `cctv1` / `-CCTV1` 落进同一个键 `cctv1`，
  而 `CCTV-16 4K` 与 `CCTV164K` 因数字块不同而不会混淆（见 get_logo_url 的数字块校验）。

【剔除的通用名】
  4k / 8k / hd / sd / tv / 18 / 1905 —— 这几个名字太泛，任何频道只要
  带"4K"就可能撞上 `4k.png`。实测 `北京卫视4K` 会误配成通用 `4k` 图标。
  宁可让这几个频道 fallback（不写 tvg-logo），也不写错图标。
"""

from typing import Dict

# 归一化键 -> 库中真实文件名（不含 .png）
_INDEX: Dict[str, str] = {
    '1905极限反转': '1905极限反转',
    '1905电影': '1905电影',
    '1pondo': '1pondo',
    '200tvbs台劇台': '200TVBS台劇台',
    '28ai': '28Ai',
    '3d电视试验': '3D电视试验',
    '3d试验': '3D试验',
    '3d试验频道': '3D试验频道',
    '4khuayuan': '4khuayuan',
    '4k乐享超清专区': '4K乐享超清专区',
    '4k地理': '4K地理',
    '4k电影': '4K电影',
    '4k自然': '4K自然',
    '4k视界专区': '4K视界专区',
    '4k超清': '4K超清',
    '4k超高清电影': '4K超高清电影',
    '4k通用': '4K通用',
    '4music': '4Music',
    '4seven': '4seven',
    '5select': '5SELECT',
    '5spike': '5Spike',
    '5spike+1': '5Spike+ 1',
    '5star': '5STAR',
    '5star+1': '5STAR+1',
    '5usa': '5 USA',
    '5usa+1': '5USA+1',
    '80s': '80s',
    '8tv': '8TV',
    '92news': '92 News',
    'a1tv': 'A1TV',
    'aajtak': 'AAJ TAK',
    'aastha': 'Aastha',
    'abcaus': 'ABCAUS',
    'abcaustralia': 'ABCAUSTRALIA',
    'abcnews': 'ABCNEWS',
    'abc新闻': 'ABC新闻',
    'abntv': 'ABN TV',
    'abomoviesthangathirai': 'ABOMOVIESTHANGATHIRAI',
    'abpnews': 'ABP News',
    'absolute': 'Absolute',
    'absolute70s': 'Absolute 70s',
    'absolute80s': 'Absolute 80s',
    'absolute90s': 'Absolute 90s',
    'abudhabitv': 'Abu Dhabi TV',
    'accnetwork': 'ACCNETWORK',
    'actstv': 'ACTSTV',
    'ae': 'A&E',
    'aehd': 'A&E HD',
    'afc': 'AFC',
    'afn': 'AFN',
    'ah': 'AH',
    'ahlebaittv': 'Ahlebait TV',
    'ahlulbayttv': 'Ahlulbayt TV',
    'aitintl': 'AIT Int_l',
    'akaalchannel': 'Akaal Channel',
    'aljazeera': 'ALJAZEERA',
    'aljazeeraeng': 'Al Jazeera Eng',
    'aljazeerahd': 'Al Jazeera HD',
    'amc': 'AMC',
    'amcfrombt': 'AMC from BT',
    'amcfrombthd': 'AMC from BTHD',
    'amcmovies': 'AMCMovies',
    'amc最爱电影': 'AMC最爱电影',
    'amc电影': 'AMC电影',
    'americanheroeschannel': 'AMERICANHEROESCHANNEL',
    'anduo': 'Anduo',
    'anhui': 'ANHUI',
    'anhui1': 'Anhui1',
    'anhui2': 'Anhui2',
    'anhui3': 'Anhui3',
    'anhui4': 'Anhui4',
    'anhui5': 'Anhui5',
    'anhui6': 'Anhui6',
    'animalplanet': 'ANIMALPLANET',
    'animalplanethdworld': 'ANIMALPLANETHDWORLD',
    'animax': 'ANIMAX',
    'animaxhd': 'ANIMAXHD',
    'animaxhk': 'ANIMAXHK',
    'aoshi1': 'Aoshi1',
    'aoshi2': 'Aoshi2',
    'aoshi3': 'Aoshi3',
    'aoshi4': 'Aoshi4',
    'aoshi5': 'Aoshi5',
    'aoshi6': 'Aoshi6',
    'aoya': 'Aoya',
    'aplustv': 'Aplus TV',
    'aqtv': 'AQTV',
    'arena': 'Arena',
    'arena2': 'ARENA2',
    'arirang': 'ARIRANG',
    'arirangtv': 'ARIRANGTV',
    'arirangtvhd': 'Arirang TV HD',
    'arirang阿里郎': 'ARIRANG阿里郎',
    'aryfamily': 'ARY Family',
    'arynews': 'ARY News',
    'aryqtv': 'ARY QTV',
    'asianfood': 'ASIANFOOD',
    'asianfoodnetwork亚洲美食': 'ASIANFOODNETWORK亚洲美食',
    'asiatravel': 'ASIATRAVEL',
    'asiazonghe': 'ASIAZONGHE',
    'astrauhddemo': 'Astra UHD Demo',
    'astro': 'Astro',
    'astroaec': 'AstroAEC',
    'astroaod': 'AstroAOD',
    'astrocricket': 'ASTROCRICKET',
    'astroiqiyi': 'Astro IQIYI',
    'astroprima': 'ASTROPRIMA',
    'astroquanjia': 'ASTROQUANJIA',
    'astroshuangxing': 'ASTROSHUANGXING',
    'astrosupersport1': 'ASTROSUPERSPORT1',
    'astrosupersport2': 'ASTROSUPERSPORT2',
    'astrosupersport3': 'ASTROSUPERSPORT3',
    'astrosupersport4': 'ASTROSUPERSPORT4',
    'astrowarna': 'ASTROWARNA',
    'astro欢喜台': 'Astro欢喜台',
    'atnbanglauk': 'ATN Bangla UK',
    'atv': 'ATV',
    'axn': 'AXN',
    'axnhk': 'AXNHK',
    'axntv': 'AXNTV',
    'axn亚洲': 'AXN亚洲',
    'axn頻道': 'AXN頻道',
    'babenation': 'Babenation',
    'babyfirst': 'BABYFIRST',
    'babytv': 'BABYTV',
    'bbc': 'BBC',
    'bbc1': 'BBC1',
    'bbc2': 'BBC2',
    'bbc3': 'BBC3',
    'bbc4': 'BBC4',
    'bbc6music': 'BBC 6 Music',
    'bbcalba': 'BBC ALBA',
    'bbcamerica': 'BBCAMERICA',
    'bbcasian': 'BBC Asian',
    'bbccbeebies': 'BBCCBEEBIES',
    'bbccymru2': 'BBC Cymru 2',
    'bbcearth': 'BBCEARTH',
    'bbcfour': 'BBC Four',
    'bbcfourhd': 'BBC Four HD',
    'bbclifestyle': 'BBCLIFESTYLE',
    'bbcnews': 'BBCNEWS',
    'bbcnewshd': 'BBC NEWS HD',
    'bbconeci': 'BBC One CI',
    'bbconeeaste': 'BBC One East E',
    'bbconeeastw': 'BBC One East W',
    'bbconeemid': 'BBC One E Mid',
    'bbconehd': 'BBC One HD',
    'bbconelon': 'BBC One Lon',
    'bbconenec': 'BBC One NE&C',
    'bbconeni': 'BBC One NI',
    'bbconenihd': 'BBC One NI HD',
    'bbconenwest': 'BBC One N West',
    'bbconeoxford': 'BBC One Oxford',
    'bbconescot': 'BBC One Scot',
    'bbconescothd': 'BBC One ScotHD',
    'bbconeseast': 'BBC One S East',
    'bbconesouth': 'BBC One South',
    'bbconeswest': 'BBC One S West',
    'bbconewales': 'BBC One Wales',
    'bbconewalhd': 'BBC One Wal HD',
    'bbconewest': 'BBC One West',
    'bbconewmid': 'BBC One W Mid',
    'bbconeykli': 'BBC One Yk&Li',
    'bbconeyorks': 'BBC One Yorks',
    'bbcparliament': 'BBC Parliament',
    'bbcr1': 'BBC R1',
    'bbcr1x': 'BBC R1X',
    'bbcr2': 'BBC R2',
    'bbcr3': 'BBC R3',
    'bbcr4ex': 'BBC R4 Ex',
    'bbcr4fm': 'BBC R4 FM',
    'bbcr4lw': 'BBC R4 LW',
    'bbcr5l': 'BBC R5L',
    'bbcr5sx': 'BBC R5SX',
    'bbcrb1': 'BBC RB1',
    'bbcrbhd': 'BBC RB HD',
    'bbcrcymru': 'BBC R Cymru',
    'bbcrfoyle': 'BBC R Foyle',
    'bbcrngael': 'BBC R n Gael',
    'bbcrscot': 'BBC R Scot.',
    'bbcrulster': 'BBC R Ulster',
    'bbcrwales': 'BBC R Wales',
    'bbcscot': 'BBCSCOT',
    'bbctwoeng': 'BBC Two Eng',
    'bbctwohd': 'BBC Two HD',
    'bbctwoni': 'BBC Two NI',
    'bbctwoscot': 'BBC Two Scot',
    'bbctwowales': 'BBC Two Wales',
    'bbcworldnews': 'BBCWORLDNEWS',
    'bbcworldnewsasia': 'BBCWORLDNEWSASIA',
    'bbcws': 'BBC WS',
    'beautifullife': 'BEAUTIFULLIFE',
    'beijing': 'BEIJING',
    'beijing0': 'Beijing0',
    'beijing1': 'Beijing1',
    'beijing10': 'Beijing10',
    'beijing2': 'Beijing2',
    'beijing3': 'Beijing3',
    'beijing4': 'Beijing4',
    'beijing5': 'Beijing5',
    'beijing6': 'Beijing6',
    'beijing7': 'Beijing7',
    'beijing8': 'Beijing8',
    'beijing9': 'Beijing9',
    'beijingjishi': 'BEIJINGJISHI',
    'beinsportsenglish2': 'BEINSPORTSENGLISH2',
    'beinsportsusa': 'BEINSPORTSUSA',
    'ben': 'BEN',
    'bestdirect': 'Best Direct',
    'bestv': 'BESTV',
    'bestv4k': 'BesTV4K',
    'bestv超级体育': 'BESTV超级体育',
    'bet': 'BET',
    'betblackenttv': 'BET_BlackEntTv',
    'bether': 'BETHER',
    'bfbsradio': 'BFBS Radio',
    'bike': 'Bike',
    'bingtuan': 'BINGTUAN',
    'blaze': 'BLAZE',
    'bloomberg': 'Bloomberg',
    'bloomberghd': 'Bloomberg HD',
    'bloombergtv': 'BLOOMBERGTV',
    'bltv': 'BLTV',
    'blueantentertainment': 'BLUEANTENTERTAINMENT',
    'blueantextreme': 'BLUEANTEXTREME',
    'bollyone': 'BOLLYONE',
    'boomerang': 'BOOMERANG',
    'boomerang+1': 'Boomerang +1',
    'boomeranghd': 'Boomerang HD',
    'boxhits': 'Box Hits',
    'boxnationhd': 'BoxNation HD',
    'boxupfront': 'Box Upfront',
    'bravo': 'BRAVO',
    'britasiatv': 'Brit Asia TV',
    'britishmuslim': 'British Muslim',
    'browseshop': 'Browse Shop',
    'brtvart': 'BRTV_ART',
    'brtvinternational': 'BRTVInternational',
    'brtv体育休闲': 'BRTV体育休闲',
    'brtv北京卫视': 'BRTV北京卫视',
    'brtv北京纪实': 'BRTV北京纪实',
    'brtv卡酷少儿': 'BRTV卡酷少儿',
    'brtv卫视': 'BRTV卫视',
    'brtv国际频道': 'BRTV国际频道',
    'brtv影视': 'BRTV影视',
    'brtv文艺': 'BRTV文艺',
    'brtv新闻': 'BRTV新闻',
    'brtv生活': 'BRTV生活',
    'brtv纪实': 'BRTV纪实',
    'brtv财经': 'BRTV财经',
    'brtv青年': 'BRTV青年',
    'btspcrt1': 'BTSPCRT1',
    'btspcrt2': 'BTSPCRT2',
    'btspcrt3': 'BTSPCRT3',
    'btsport1': 'BT Sport 1',
    'btsport1hd': 'BT Sport 1 HD',
    'btsport2': 'BT Sport 2',
    'btsport2hd': 'BT Sport 2 HD',
    'btsportespn': 'BT Sport ESPN',
    'btsptespnhd': 'BTSpt ESPNHD',
    'btv体育': 'BTV体育',
    'btv体育休闲': 'BTV体育休闲',
    'btv冬奥纪实': 'BTV冬奥纪实',
    'btv卡酷少儿': 'BTV卡酷少儿',
    'btv影视': 'BTV影视',
    'btv文艺': 'BTV文艺',
    'btv新闻': 'BTV新闻',
    'btv生活': 'BTV生活',
    'btv科教': 'BTV科教',
    'btv纪实': 'BTV纪实',
    'btv财经': 'BTV财经',
    'btv青年': 'BTV青年',
    'c+': 'C+',
    'capital': 'Capital',
    'capitaltv': 'CAPITAL TV',
    'capitalxtra': 'Capital XTRA',
    'cartoonito': 'CARTOONITO',
    'cartoonnethd': 'Cartoon Net HD',
    'cartoonnetwork': 'CARTOONNETWORK',
    'cartoonnetwrk': 'Cartoon_Netwrk',
    'catchplay': 'CATCHPLAY',
    'catchplay1': 'CatchPlay1',
    'catchplay2': 'CatchPlay2',
    'catchplaybeyond': 'CATCHPLAYBEYOND',
    'catchplay电影': 'CATCHPLAY电影',
    'catchplay电影台': 'CatchPlay电影台',
    'cbbc': 'CBBC',
    'cbbchd': 'CBBC HD',
    'cbchd': 'CBC HD',
    'cbeebies': 'CBEEBIES',
    'cbeebieshd': 'CBeebies HD',
    'cbn1': 'CBN1',
    'cbn2': 'CBN2',
    'cbn3': 'CBN3',
    'cbn4': 'CBN4',
    'cbn幸福剧场': 'CBN幸福剧场',
    'cbn幸福娱乐': 'CBN幸福娱乐',
    'cbn每日影院': 'CBN每日影院',
    'cbn风尚生活': 'CBN风尚生活',
    'cbs': 'CBS',
    'cbsaction': 'CBS Action',
    'cbsdrama': 'CBS Drama',
    'cbsn': 'CBSN',
    'cbsreality': 'CBS Reality',
    'cbsreality+1': 'CBS Reality+1',
    'cbssports': 'CBSSPORTS',
    'cbssportsnetwork': 'CBSSPORTSNETWORK',
    'ccm': 'CCM',
    'cctv1': 'CCTV1',
    'cctv10': 'CCTV10',
    'cctv11': 'CCTV11',
    'cctv11戏曲': 'CCTV-11戏曲',
    'cctv12': 'CCTV12',
    'cctv13': 'CCTV13',
    'cctv14': 'CCTV14',
    'cctv15': 'CCTV15',
    'cctv16': 'CCTV16',
    'cctv164k': 'CCTV164K',
    'cctv17': 'CCTV17',
    'cctv2': 'CCTV2',
    'cctv3': 'CCTV3',
    'cctv3d': 'CCTV3D',
    'cctv4': 'CCTV4',
    'cctv4ame': 'CCTV4AME',
    'cctv4euo': 'CCTV4EUO',
    'cctv4k': 'CCTV4K',
    'cctv4k超高清': 'CCTV4K超高清',
    'cctv4欧洲': 'CCTV4欧洲',
    'cctv4美洲': 'CCTV4美洲',
    'cctv5': 'CCTV5',
    'cctv5+': 'CCTV5+',
    'cctv5plus': 'CCTV5plus',
    'cctv6': 'CCTV6',
    'cctv7': 'CCTV7',
    'cctv8': 'CCTV8',
    'cctv8k': 'CCTV8K',
    'cctv9': 'CCTV9',
    'cctv世界地理': 'CCTV世界地理',
    'cctv中学生': 'CCTV中学生',
    'cctv卫生健康': 'CCTV卫生健康',
    'cctv发现之旅': 'CCTV发现之旅',
    'cctv央视台球': 'CCTV央视台球',
    'cctv央视太球': 'CCTV央视太球',
    'cctv女性时尚': 'CCTV女性时尚',
    'cctv娱乐': 'CCTV娱乐',
    'cctv怀旧剧场': 'CCTV怀旧剧场',
    'cctv戏曲': 'CCTV戏曲',
    'cctv新科动漫': 'CCTV新科动漫',
    'cctv电视指南': 'CCTV电视指南',
    'cctv移动': 'CCTV移动',
    'cctv第一剧场': 'CCTV第一剧场',
    'cctv老故事': 'CCTV老故事',
    'cctv证券资讯': 'CCTV证券资讯',
    'cctv风云剧场': 'CCTV风云剧场',
    'cctv风云足球': 'CCTV风云足球',
    'cctv风云音乐': 'CCTV风云音乐',
    'cctv高尔夫网球': 'CCTV高尔夫网球',
    'cdtv1': 'CDTV1',
    'cdtv2': 'CDTV2',
    'cdtv3': 'CDTV3',
    'cdtv4': 'CDTV4',
    'cdtv5': 'CDTV5',
    'cdtv6': 'CDTV6',
    'cetv1': 'CETV1',
    'cetv2': 'CETV2',
    'cetv3': 'CETV3',
    'cetv4': 'CETV4',
    'cetv早期教育': 'CETV早期教育',
    'cgtn': 'CGTN',
    'cgtnalby': 'CGTNalby',
    'cgtndoc': 'CGTNDOC',
    'cgtndocumentary': 'CGTNDOCUMENTARY',
    'cgtnespsnol': 'CGTN espsnol',
    'cgtney': 'CGTNey',
    'cgtnfy': 'CGTNfy',
    'cgtnjilu': 'CGTNjilu',
    'cgtnxbyy': 'CGTNxbyy',
    'cgtn俄语': 'CGTN俄语',
    'cgtn法语': 'CGTN法语',
    'cgtn纪录': 'CGTN纪录',
    'cgtn英語': 'CGTN英語',
    'cgtn英语': 'CGTN英语',
    'cgtn西班牙语': 'CGTN西班牙语',
    'cgtn西语': 'CGTN西语',
    'cgtn记录': 'CGTN记录',
    'cgtn阿拉伯语': 'CGTN阿拉伯语',
    'cgtn阿语': 'CGTN阿语',
    'cgtv': 'CGTV',
    'challenge': 'Challenge',
    'challenge+1': 'Challenge+1',
    'championtv1': 'CHAMPIONTV1',
    'championtv2': 'CHAMPIONTV2',
    'channel4': 'Channel 4',
    'channel4+1': 'Channel 4+1',
    'channel44': 'Channel 44',
    'channel4hd': 'Channel 4 HD',
    'channel5': 'Channel 5',
    'channel5+1': 'Channel 5+1',
    'channel5+24': 'Channel 5+24',
    'channel5hd': 'Channel 5 HD',
    'channel8': 'Channel-8',
    'channel8hd': 'Channel 8 HD',
    'channelaka': 'Channel AKA',
    'channelasia': 'ChannelAsia',
    'channeli': 'Channel i',
    'channelnewsasia': 'CHANNELNEWSASIA',
    'channels24': 'Channels 24',
    'channeluhd': 'Channel U HD',
    'channelv': 'CHANNELV',
    'chartshowhits': 'Chartshow Hits',
    'chartshowtv': 'Chart Show TV',
    'chartshwdnce': 'Chartshw Dnce',
    'chatbox': 'Chat Box',
    'chc1': 'CHC1',
    'chc2': 'CHC2',
    'chc3': 'CHC3',
    'chc动作电影': 'CHC动作电影',
    'chc家庭影院': 'CHC家庭影院',
    'chc家庭电影': 'CHC家庭电影',
    'chc影迷电影': 'CHC影迷电影',
    'chc高清电影': 'CHC高清电影',
    'chengdu1': 'Chengdu1',
    'chengdu2': 'Chengdu2',
    'chengdu3': 'Chengdu3',
    'chengdu4': 'Chengdu4',
    'chengdu5': 'Chengdu5',
    'chengdu6': 'Chengdu6',
    'chengdu7': 'Chengdu7',
    'chilledtv': 'Chilled TV',
    'chllineup': 'Chl Line-up',
    'chongqing': 'CHONGQING',
    'chongqing1': 'Chongqing1',
    'chongqing2': 'Chongqing2',
    'chongqing3': 'Chongqing3',
    'chongqing4': 'Chongqing4',
    'chongqing5': 'Chongqing5',
    'chongqing6': 'Chongqing6',
    'chongqing7': 'Chongqing7',
    'chongqing8': 'Chongqing8',
    'chstv': 'CHSTV',
    'chtv': 'CHTV',
    'ci': 'CI',
    'cibn': 'CIBN',
    'cibn01': 'CIBN01',
    'cibn02': 'CIBN02',
    'cibn03': 'CIBN03',
    'cibn04': 'CIBN04',
    'cibn05': 'CIBN05',
    'cibn06': 'CIBN06',
    'cibn07': 'CIBN07',
    'cibn08': 'CIBN08',
    'cibn09': 'CIBN09',
    'cibn10': 'CIBN10',
    'cibn军事': 'CIBN军事',
    'cibn动作影院': 'CIBN动作影院',
    'cibn动画乐园': 'CIBN动画乐园',
    'cibn古装剧场': 'CIBN古装剧场',
    'cibn喜剧影院': 'CIBN喜剧影院',
    'cibn好莱坞': 'CIBN好莱坞',
    'cibn微电影': 'CIBN微电影',
    'cibn情感影院': 'CIBN情感影院',
    'cibn汽车': 'CIBN汽车',
    'cibn流经岁月': 'CIBN流经岁月',
    'cibn流金岁月': 'CIBN流金岁月',
    'cibn电影': 'CIBN电影',
    'cibn留学世界': 'CIBN留学世界',
    'cibn真人秀': 'CIBN真人秀',
    'cibn精品影院': 'CIBN精品影院',
    'cibn纪录片': 'CIBN纪录片',
    'cibn经典剧场': 'CIBN经典剧场',
    'cibn综合': 'CIBN综合',
    'cibn艺术院线': 'CIBN艺术院线',
    'cibn轮播': 'CIBN轮播',
    'cibn通用': 'CIBN通用',
    'cibn院线大片': 'CIBN院线大片',
    'cibn风尚运动': 'CIBN风尚运动',
    'cibn骄阳剧场': 'CIBN骄阳剧场',
    'cinemaworld': 'CINEMAWORLD',
    'cinemax': 'CINEMAX',
    'cinemaxhd': 'CINEMAXHD',
    'cinemaxwest': 'CINEMAXWEST',
    'citv': 'CITV',
    'city都市剧场': 'CITY都市剧场',
    'ci罪案侦查': 'CI罪案侦查',
    'ci罪案侦查频道': 'CI罪案侦查频道',
    'classica古典乐': 'CLASSICA古典乐',
    'classicfm': 'Classic FM',
    'classicrock': 'Classic Rock',
    'cltv': 'CLTV',
    'clublandtv': 'Clubland TV',
    'cmt': 'CMT',
    'cmusic': 'CMUSIC',
    'cn+1': 'CN+1',
    'cna': 'CNA',
    'cna亚洲新闻': 'CNA亚洲新闻',
    'cnbc': 'CNBC',
    'cnbcasia': 'CNBCASIA',
    'cnbcasia财经': 'CNBCASIA财经',
    'cnbcasia财经台': 'CNBCASIA财经台',
    'cnbchongkong': 'CNBCHONGKONG',
    'cnc': 'CNC',
    'cncartoon': 'CNCartoon',
    'cnccn': 'CNCCN',
    'cncen': 'CNCEN',
    'cncworld': 'CNC World',
    'cndfxzl': 'CNDfxzl',
    'cndlgs': 'CNDlgs',
    'cndxkdm': 'CNDxkdm',
    'cndzqzx': 'CNDzqzx',
    'cndzxs': 'CNDzxs',
    'cnex': 'CNEX',
    'cnn': 'CNN',
    'cnnhd': 'CNN HD',
    'cnninternational': 'CNNINTERNATIONAL',
    'cnnnews': 'CNNNEWS',
    'cnn国际新闻': 'CNN国际新闻',
    'cn卡通': 'CN卡通',
    'cn卡通频道': 'CN卡通频道',
    'colorstamil': 'COLORSTAMIL',
    'comedycent+1': 'ComedyCent+1',
    'comedycenthd': 'ComedyCentHD',
    'comedycentral': 'COMEDYCENTRAL',
    'comedycentralasia': 'COMEDY-CENTRAL-ASIA',
    'comedyxtra': 'ComedyXtra',
    'comedyxtra+1': 'ComedyXtra+1',
    'community': 'Community',
    'cookingchannel': 'COOKINGCHANNEL',
    'costartv': 'COSTARTV',
    'cqccn': 'CQCCN',
    'craftextra': 'Craft Extra',
    'createcraft': 'Create & Craft',
    'crime': 'CRIME',
    'crime+inv': 'Crime+Inv',
    'crimeinvestigation': 'CRIMEINVESTIGATION',
    'crimeplus': 'Crimeplus',
    'cruise1sttv': 'Cruise1st.tv',
    'cs': 'CS',
    'cspan': 'CSPAN',
    'cspan2': 'CSPAN2',
    'cti1': 'CTI1',
    'cti2': 'CTI2',
    'cti3': 'CTI3',
    'cti4': 'CTI4',
    'cti5': 'CTI5',
    'ctientertainment': 'CTIENTERTAINMENT',
    'ctivariety': 'CTIVARIETY',
    'cts': 'CTS',
    'cts1': 'CTS1',
    'cts2': 'CTS2',
    'ctv': 'CTV',
    'ctv1': 'CTV1',
    'ctv2': 'CTV2',
    'ctv3': 'CTV3',
    'cyczonghe': 'CYCzonghe',
    'cyzhtv': 'CYZHTV',
    'daai': 'DAAI',
    'daai1': 'Daai1',
    'daai2': 'DAAI2',
    'daai3': 'Daai3',
    'dalian1': 'Dalian1',
    'dalian2': 'Dalian2',
    'dalian3': 'Dalian3',
    'dalian4': 'Dalian4',
    'dalian5': 'Dalian5',
    'dalian6': 'Dalian6',
    'dalian7': 'Dalian7',
    'dave': 'Dave',
    'davehd': 'Dave HD',
    'davinci': 'DAVINCI',
    'daystarhd': 'DAYSTAR HD',
    'dazn': 'DAZN',
    'desiradio': 'Desi Radio',
    'destinationamerica': 'DESTINATIONAMERICA',
    'dianjingtiantang': 'DIANJINGTIANTANG',
    'dirtytalk': 'Dirty Talk',
    'dischistory': 'Disc.History',
    'discovery': 'DISCOVERY',
    'discovery+1': 'Discovery+1',
    'discovery1': 'Discovery1',
    'discovery2': 'Discovery2',
    'discoveryasia': 'DISCOVERYASIA',
    'discoverychannel': 'DISCOVERYCHANNEL',
    'discoverydmax': 'DISCOVERYDMAX',
    'discoveryeve': 'DISCOVERYEVE',
    'discoveryfamilychannel': 'DISCOVERYFAMILYCHANNEL',
    'discoveryhd': 'DISCOVERYHD',
    'discoverylife': 'DISCOVERYLIFE',
    'discoveryscience': 'DISCOVERYSCIENCE',
    'discovery亚洲': 'DISCOVERY亚洲',
    'discovery探索日本': 'Discovery探索日本',
    'discovery科学': 'DISCOVERY科学',
    'discovery科学频道': 'Discovery科学频道',
    'discscience': 'Disc.Science',
    'discturbo': 'Disc.Turbo',
    'disney': 'DISNEY',
    'disney1': 'Disney1',
    'disney2': 'Disney2',
    'disneychannel': 'DISNEYCHANNEL',
    'disneychnl': 'Disney Chnl',
    'disneychnl+1': 'Disney Chnl+1',
    'disneychnlhd': 'Disney Chnl HD',
    'disneyjnrhd': 'Disney Jnr HD',
    'disneyjunior': 'DISNEYJUNIOR',
    'disneyxd': 'DISNEYXD',
    'disneyxd+1': 'Disney XD+1',
    'disneyxdhd': 'Disney XD HD',
    'diva': 'DIVA',
    'diyicaijing': 'DIYICAIJING',
    'dmax': 'DMAX',
    'dmhkrwc': 'DMHKRWC',
    'dog狗': 'DOG狗',
    'dog狗频道': 'Dog狗频道',
    'dongfang': 'DONGFANG',
    'dongfeng': 'Dongfeng',
    'dongnan': 'DONGNAN',
    'dox1': 'DOX1',
    'dox10': 'DOX10',
    'dox11': 'DOX11',
    'dox12': 'DOX12',
    'dox2': 'DOX2',
    'dox3': 'DOX3',
    'dox4': 'DOX4',
    'dox4k': 'DOX4K',
    'dox5': 'DOX5',
    'dox6': 'DOX6',
    'dox7': 'DOX7',
    'dox8': 'DOX8',
    'dox9': 'DOX9',
    'doxcinema': 'DOXCINEMA',
    'doxjuchang': 'DOXJUCHANG',
    'doxtv': 'DOXTV',
    'doxtv高清': 'DOXTV高清',
    'doxxinyi': 'DOXXINYI',
    'doxxinzhi': 'DOXXINZHI',
    'doxyaqu': 'DOXYAQU',
    'doxyijia': 'DOXYIJIA',
    'doxyinghua': 'DOXYINGHUA',
    'doxyinglun': 'DOXYINGLUN',
    'dox剧场': 'DOX剧场',
    'dox怡家': 'DOX怡家',
    'dox新知': 'DOX新知',
    'dox新艺': 'DOX新艺',
    'dox映画': 'DOX映画',
    'dox环映': 'DOX环映',
    'dox红色经典': 'DOX红色经典',
    'dox美剧': 'DOX美剧',
    'dox英伦': 'DOX英伦',
    'dox院线': 'DOX院线',
    'dox雅趣': 'DOX雅趣',
    'drama': 'DRAMA',
    'dreamworks': 'DREAMWORKS',
    'dreamworks梦工厂动画': 'DREAMWORKS梦工厂动画',
    'dunyanews': 'Dunya News',
    'dv生活': 'DV生活',
    'dw': 'DW',
    'dwchannel': 'DWChannel',
    'dw德国之声': 'DW德国之声',
    'e': 'E!',
    'e4': 'E4',
    'e4+1': 'E4+1',
    'e4hd': 'E4 HD',
    'eatasports1': 'EATASPORTS1',
    'eatasports3': 'EATASPORTS3',
    'ebc1': 'EBC1',
    'ebc10': 'EBC10',
    'ebc11': 'EBC11',
    'ebc2': 'EBC2',
    'ebc3': 'EBC3',
    'ebc4': 'EBC4',
    'ebc5': 'EBC5',
    'ebc6': 'EBC6',
    'ebc7': 'EBC7',
    'ebc8': 'EBC8',
    'ebc9': 'EBC9',
    'ebcasianews': 'EBCASIANEWS',
    'ebcasiaweishi': 'EBCASIAWEISHI',
    'ebcdrama': 'EBCDRAMA',
    'ebcfinancialnews': 'EBCFINANCIALNEWS',
    'ebcmovies': 'EBCMOVIES',
    'ebcnews': 'EBCNEWS',
    'ebcsuper': 'EBCSUPER',
    'ebcvariety': 'EBCVARIETY',
    'ebcwesternmovies': 'EBCWESTERNMOVIES',
    'ebcyoyotv': 'EBCYOYOTV',
    'ebs': 'EBS',
    'eentertainment': 'E!ENTERTAINMENT',
    'eftv': 'EFTV',
    'eftvcaijing': 'EFTVcaijing',
    'eftv运通财经': 'EFTV运通财经',
    'eftv运通财经台': 'EFTV运通财经台',
    'eleven+': 'ELEVEN+',
    'eleven1': 'ELEVEN1',
    'eleven2': 'ELEVEN2',
    'eleven3': 'ELEVEN3',
    'eleven4': 'Eleven4',
    'elevenplus': 'ELEVENPLUS',
    'elevensports1': 'ELEVENSPORTS1',
    'elevensports2': 'ELEVENSPORTS2',
    'eleven体育一': 'ELEVEN体育一',
    'eleven体育二': 'ELEVEN体育二',
    'elta1': 'ELTA1',
    'elta10': 'ELTA10',
    'elta11': 'ELTA11',
    'elta12': 'ELTA12',
    'elta13': 'ELTA13',
    'elta2': 'ELTA2',
    'elta3': 'ELTA3',
    'elta4': 'ELTA4',
    'elta5': 'ELTA5',
    'elta6': 'ELTA6',
    'elta7': 'ELTA7',
    'elta8': 'ELTA8',
    'elta9': 'ELTA9',
    'eltaent': 'ELTAENT',
    'eltasports2': 'ELTASPORTS2',
    'eltayingju': 'ELTAYINGJU',
    'eltazonghehd': 'ELTAZONGHEHD',
    'elta体育': 'ELTA体育',
    'elta体育1': 'ELTA体育1',
    'elta体育2': 'ELTA体育2',
    'elta体育3': 'ELTA体育3',
    'elta体育4': 'ELTA体育4',
    'elta体育max1': 'ELTA体育MAX1',
    'elta体育max2': 'ELTA体育MAX2',
    'elta体育max3': 'ELTA体育MAX3',
    'elta体育max4': 'ELTA体育MAX4',
    'elta原音2': 'ELTA原音2',
    'elta原音3': 'ELTA原音3',
    'elta原音音1': 'ELTA原音音1',
    'elta奥运1': 'ELTA奥运1',
    'elta奥运2': 'ELTA奥运2',
    'elta奥运3': 'ELTA奥运3',
    'elta奥运4': 'ELTA奥运4',
    'elta奥运5': 'ELTA奥运5',
    'elta奥运6': 'ELTA奥运6',
    'elta奥运7': 'ELTA奥运7',
    'elta娱乐': 'ELTA娱乐',
    'elta影剧': 'ELTA影剧',
    'elta日韩': 'ELTA日韩',
    'elta生活旅游': 'ELTA生活旅游',
    'elta生活英语': 'ELTA生活英语',
    'elta综合': 'ELTA综合',
    'eltv': 'ELTV',
    'eltv生活英语': 'ELTV生活英语',
    'eltv生活英语台': 'ELTV生活英语台',
    'emanchannel': 'Eman Channel',
    'emeidianying': 'EMEIDIANYING',
    'era1': 'ERA1',
    'era2': 'ERA2',
    'espn': 'ESPN',
    'espn2': 'ESPN2',
    'espnnews': 'ESPNNEWS',
    'espnu': 'ESPNU',
    'etoday': 'ETODAY',
    'ettoday': 'ETTODAY',
    'ettoday综合': 'ETTODAY综合',
    'ettoday综合台': 'ETtoday综合台',
    'euronews': 'EURONEWS',
    'eurosport': 'EUROSPORT',
    'eurosport1': 'EUROSPORT1',
    'eurosport2': 'EUROSPORT2',
    'eve': 'EVE',
    'eve频道': 'EVE频道',
    'ewtn': 'EWTN',
    'ewtncatholic': 'EWTN Catholic',
    'eye1': 'EYE1',
    'eye2': 'EYE2',
    'eyelvyou': 'EYELVYOU',
    'eyetv戏剧': 'EYETV戏剧',
    'eyetv戏剧台': 'EYETV戏剧台',
    'eyetv旅游': 'EYETV旅游',
    'eyexiju': 'EYEXIJU',
    'eye戏剧': 'EYE戏剧',
    'eye旅游': 'EYE旅游',
    'e彩虹': 'E彩虹',
    'fametv': 'FAME TV',
    'fans1': 'FANS1',
    'fans2': 'FANS2',
    'fashionbox': 'FASHIONBOX',
    'fashionone': 'FASHIONONE',
    'fashiontv': 'FASHIONTV',
    'fei': 'FEI',
    'fenghuangxianggang': 'FENGHUANGXIANGGANG',
    'fenghuangzhongwen': 'FENGHUANGZHONGWEN',
    'fenghuangzixun': 'FENGHUANGZIXUN',
    'fightnetwork': 'FIGHTNETWORK',
    'fightsporthd': 'FIGHTSPORTHD',
    'fightsports': 'FIGHTSPORTS',
    'firstmoives': 'FIRSTMOIVES',
}

# 手工补充项：优先级**高于** _INDEX。
# 用途：库里有多个同义文件时指定首选；或预先填好将来会加的文件。
_EXTRA: Dict[str, str] = {
    # 例："guangxi": "广西卫视",
}


def build_index() -> Dict[str, str]:
    """返回合并后的匹配索引（副本，调用方可安全改写）。"""
    idx = dict(_INDEX)
    idx.update(_EXTRA)
    return idx


def normalize_key(name: str) -> str:
    """
    归一化频道名/文件名 -> 匹配键。

    Args:
        name: 原始名（如 "CCTV-1"、"H265-CCTV-2高清4M"）。

    Returns:
        归一化键（如 "cctv1"、"h265cctv2高清4m"）。
    """
    import re as _re
    return _re.sub(r"[^0-9a-z\u4e00-\u9fff+]+", "", (name or "").strip().lower())
